package xrechnung

/////////////////////////////////////////////////////////////////
//Code generated by chidley https://github.com/gnewton/chidley //
/////////////////////////////////////////////////////////////////

import (
	"encoding/xml"
)

///////////////////////////
/// structs
///////////////////////////

type CAccountingCustomerParty__cac struct {
	XMLName     xml.Name    `xml:"AccountingCustomerParty,omitempty" json:"AccountingCustomerParty,omitempty"`
	CParty__cac CParty__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 Party,omitempty" json:"Party,omitempty"`
}

type CAccountingSupplierParty__cac struct {
	XMLName     xml.Name    `xml:"AccountingSupplierParty,omitempty" json:"AccountingSupplierParty,omitempty"`
	CParty__cac CParty__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 Party,omitempty" json:"Party,omitempty"`
}

type CClassifiedTaxCategory__cac struct {
	XMLName         xml.Name        `xml:"ClassifiedTaxCategory,omitempty" json:"ClassifiedTaxCategory,omitempty"`
	CID__cbc        CID__cbc        `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ID,omitempty" json:"ID,omitempty"`
	CPercent__cbc   CPercent__cbc   `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Percent,omitempty" json:"Percent,omitempty"`
	CTaxScheme__cac CTaxScheme__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 TaxScheme,omitempty" json:"TaxScheme,omitempty"`
}

type CCommodityClassification__cac struct {
	XMLName                      xml.Name                     `xml:"CommodityClassification,omitempty" json:"CommodityClassification,omitempty"`
	CItemClassificationCode__cbc CItemClassificationCode__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ItemClassificationCode,omitempty" json:"ItemClassificationCode,omitempty"`
}

type CContact__cac struct {
	XMLName              xml.Name             `xml:"Contact,omitempty" json:"Contact,omitempty"`
	CElectronicMail__cbc CElectronicMail__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ElectronicMail,omitempty" json:"ElectronicMail,omitempty"`
	CName__cbc           CName__cbc           `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Name,omitempty" json:"Name,omitempty"`
	CTelephone__cbc      CTelephone__cbc      `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Telephone,omitempty" json:"Telephone,omitempty"`
}

type CCountry__cac struct {
	XMLName                  xml.Name                 `xml:"Country,omitempty" json:"Country,omitempty"`
	CIdentificationCode__cbc CIdentificationCode__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 IdentificationCode,omitempty" json:"IdentificationCode,omitempty"`
}

type CInvoiceLine__cac struct {
	XMLName                   xml.Name                  `xml:"InvoiceLine,omitempty" json:"InvoiceLine,omitempty"`
	CID__cbc                  CID__cbc                  `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ID,omitempty" json:"ID,omitempty"`
	CInvoicePeriod__cac       CInvoicePeriod__cac       `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 InvoicePeriod,omitempty" json:"InvoicePeriod,omitempty"`
	CInvoicedQuantity__cbc    CInvoicedQuantity__cbc    `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 InvoicedQuantity,omitempty" json:"InvoicedQuantity,omitempty"`
	CItem__cac                CItem__cac                `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 Item,omitempty" json:"Item,omitempty"`
	CLineExtensionAmount__cbc CLineExtensionAmount__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 LineExtensionAmount,omitempty" json:"LineExtensionAmount,omitempty"`
	CNote__cbc                CNote__cbc                `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Note,omitempty" json:"Note,omitempty"`
	COrderLineReference__cac  COrderLineReference__cac  `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 OrderLineReference,omitempty" json:"OrderLineReference,omitempty"`
	CPrice__cac               CPrice__cac               `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 Price,omitempty" json:"Price,omitempty"`
}

type CInvoicePeriod__cac struct {
	XMLName         xml.Name        `xml:"InvoicePeriod,omitempty" json:"InvoicePeriod,omitempty"`
	CEndDate__cbc   CEndDate__cbc   `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 EndDate,omitempty" json:"EndDate,omitempty"`
	CStartDate__cbc CStartDate__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 StartDate,omitempty" json:"StartDate,omitempty"`
}

type CItem__cac struct {
	XMLName                         xml.Name                        `xml:"Item,omitempty" json:"Item,omitempty"`
	CClassifiedTaxCategory__cac     CClassifiedTaxCategory__cac     `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 ClassifiedTaxCategory,omitempty" json:"ClassifiedTaxCategory,omitempty"`
	CCommodityClassification__cac   CCommodityClassification__cac   `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 CommodityClassification,omitempty" json:"CommodityClassification,omitempty"`
	CDescription__cbc               CDescription__cbc               `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Description,omitempty" json:"Description,omitempty"`
	CName__cbc                      CName__cbc                      `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Name,omitempty" json:"Name,omitempty"`
	CSellersItemIdentification__cac CSellersItemIdentification__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 SellersItemIdentification,omitempty" json:"SellersItemIdentification,omitempty"`
}

type CLegalMonetaryTotal__cac struct {
	XMLName                   xml.Name                  `xml:"LegalMonetaryTotal,omitempty" json:"LegalMonetaryTotal,omitempty"`
	CLineExtensionAmount__cbc CLineExtensionAmount__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 LineExtensionAmount,omitempty" json:"LineExtensionAmount,omitempty"`
	CPayableAmount__cbc       CPayableAmount__cbc       `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 PayableAmount,omitempty" json:"PayableAmount,omitempty"`
	CTaxExclusiveAmount__cbc  CTaxExclusiveAmount__cbc  `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 TaxExclusiveAmount,omitempty" json:"TaxExclusiveAmount,omitempty"`
	CTaxInclusiveAmount__cbc  CTaxInclusiveAmount__cbc  `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 TaxInclusiveAmount,omitempty" json:"TaxInclusiveAmount,omitempty"`
}

type COrderLineReference__cac struct {
	XMLName      xml.Name     `xml:"OrderLineReference,omitempty" json:"OrderLineReference,omitempty"`
	CLineID__cbc CLineID__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 LineID,omitempty" json:"LineID,omitempty"`
}

type CParty__cac struct {
	XMLName                   xml.Name                  `xml:"Party,omitempty" json:"Party,omitempty"`
	CContact__cac             CContact__cac             `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 Contact,omitempty" json:"Contact,omitempty"`
	CPartyIdentification__cac CPartyIdentification__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 PartyIdentification,omitempty" json:"PartyIdentification,omitempty"`
	CPartyLegalEntity__cac    CPartyLegalEntity__cac    `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 PartyLegalEntity,omitempty" json:"PartyLegalEntity,omitempty"`
	CPartyName__cac           CPartyName__cac           `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 PartyName,omitempty" json:"PartyName,omitempty"`
	CPartyTaxScheme__cac      CPartyTaxScheme__cac      `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 PartyTaxScheme,omitempty" json:"PartyTaxScheme,omitempty"`
	CPostalAddress__cac       CPostalAddress__cac       `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 PostalAddress,omitempty" json:"PostalAddress,omitempty"`
}

type CPartyIdentification__cac struct {
	XMLName  xml.Name `xml:"PartyIdentification,omitempty" json:"PartyIdentification,omitempty"`
	CID__cbc CID__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ID,omitempty" json:"ID,omitempty"`
}

type CPartyLegalEntity__cac struct {
	XMLName                xml.Name               `xml:"PartyLegalEntity,omitempty" json:"PartyLegalEntity,omitempty"`
	CCompanyID__cbc        CCompanyID__cbc        `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 CompanyID,omitempty" json:"CompanyID,omitempty"`
	CCompanyLegalForm__cbc CCompanyLegalForm__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 CompanyLegalForm,omitempty" json:"CompanyLegalForm,omitempty"`
	CRegistrationName__cbc CRegistrationName__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 RegistrationName,omitempty" json:"RegistrationName,omitempty"`
}

type CPartyName__cac struct {
	XMLName    xml.Name   `xml:"PartyName,omitempty" json:"PartyName,omitempty"`
	CName__cbc CName__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Name,omitempty" json:"Name,omitempty"`
}

type CPartyTaxScheme__cac struct {
	XMLName         xml.Name        `xml:"PartyTaxScheme,omitempty" json:"PartyTaxScheme,omitempty"`
	CCompanyID__cbc CCompanyID__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 CompanyID,omitempty" json:"CompanyID,omitempty"`
	CTaxScheme__cac CTaxScheme__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 TaxScheme,omitempty" json:"TaxScheme,omitempty"`
}

type CPayeeFinancialAccount__cac struct {
	XMLName  xml.Name `xml:"PayeeFinancialAccount,omitempty" json:"PayeeFinancialAccount,omitempty"`
	CID__cbc CID__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ID,omitempty" json:"ID,omitempty"`
}

type CPaymentMeans__cac struct {
	XMLName                     xml.Name                    `xml:"PaymentMeans,omitempty" json:"PaymentMeans,omitempty"`
	CPayeeFinancialAccount__cac CPayeeFinancialAccount__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 PayeeFinancialAccount,omitempty" json:"PayeeFinancialAccount,omitempty"`
	CPaymentMeansCode__cbc      CPaymentMeansCode__cbc      `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 PaymentMeansCode,omitempty" json:"PaymentMeansCode,omitempty"`
}

type CPaymentTerms__cac struct {
	XMLName    xml.Name    `xml:"PaymentTerms,omitempty" json:"PaymentTerms,omitempty"`
	CNote__cbc *CNote__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Note,omitempty" json:"Note,omitempty"`
}

type CPostalAddress__cac struct {
	XMLName          xml.Name         `xml:"PostalAddress,omitempty" json:"PostalAddress,omitempty"`
	CCityName__cbc   CCityName__cbc   `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 CityName,omitempty" json:"CityName,omitempty"`
	CCountry__cac    CCountry__cac    `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 Country,omitempty" json:"Country,omitempty"`
	CPostalZone__cbc CPostalZone__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 PostalZone,omitempty" json:"PostalZone,omitempty"`
	CStreetName__cbc CStreetName__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 StreetName,omitempty" json:"StreetName,omitempty"`
}

type CPrice__cac struct {
	XMLName           xml.Name          `xml:"Price,omitempty" json:"Price,omitempty"`
	CPriceAmount__cbc CPriceAmount__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 PriceAmount,omitempty" json:"PriceAmount,omitempty"`
}

type CSellersItemIdentification__cac struct {
	XMLName  xml.Name `xml:"SellersItemIdentification,omitempty" json:"SellersItemIdentification,omitempty"`
	CID__cbc CID__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ID,omitempty" json:"ID,omitempty"`
}

type CTaxCategory__cac struct {
	XMLName         xml.Name        `xml:"TaxCategory,omitempty" json:"TaxCategory,omitempty"`
	CID__cbc        CID__cbc        `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ID,omitempty" json:"ID,omitempty"`
	CPercent__cbc   CPercent__cbc   `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Percent,omitempty" json:"Percent,omitempty"`
	CTaxScheme__cac CTaxScheme__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 TaxScheme,omitempty" json:"TaxScheme,omitempty"`
}

type CTaxScheme__cac struct {
	XMLName  xml.Name `xml:"TaxScheme,omitempty" json:"TaxScheme,omitempty"`
	CID__cbc CID__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ID,omitempty" json:"ID,omitempty"`
}

type CTaxSubtotal__cac struct {
	XMLName             xml.Name            `xml:"TaxSubtotal,omitempty" json:"TaxSubtotal,omitempty"`
	CTaxAmount__cbc     CTaxAmount__cbc     `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 TaxAmount,omitempty" json:"TaxAmount,omitempty"`
	CTaxCategory__cac   CTaxCategory__cac   `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 TaxCategory,omitempty" json:"TaxCategory,omitempty"`
	CTaxableAmount__cbc CTaxableAmount__cbc `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 TaxableAmount,omitempty" json:"TaxableAmount,omitempty"`
}

type CTaxTotal__cac struct {
	XMLName           xml.Name          `xml:"TaxTotal,omitempty" json:"TaxTotal,omitempty"`
	CTaxAmount__cbc   CTaxAmount__cbc   `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 TaxAmount,omitempty" json:"TaxAmount,omitempty"`
	CTaxSubtotal__cac CTaxSubtotal__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 TaxSubtotal,omitempty" json:"TaxSubtotal,omitempty"`
}

type CBuyerReference__cbc struct {
	XMLName        xml.Name `xml:"BuyerReference,omitempty" json:"BuyerReference,omitempty"`
	BuyerReference string   `xml:",chardata" json:",omitempty"`
}

type CCityName__cbc struct {
	XMLName  xml.Name `xml:"CityName,omitempty" json:"CityName,omitempty"`
	CityName string   `xml:",chardata" json:",omitempty"`
}

type CCompanyID__cbc struct {
	XMLName   xml.Name `xml:"CompanyID,omitempty" json:"CompanyID,omitempty"`
	CompanyID string   `xml:",chardata" json:",omitempty"`
}

type CCompanyLegalForm__cbc struct {
	XMLName          xml.Name `xml:"CompanyLegalForm,omitempty" json:"CompanyLegalForm,omitempty"`
	CompanyLegalForm string   `xml:",chardata" json:",omitempty"`
}

type CCustomizationID__cbc struct {
	XMLName         xml.Name `xml:"CustomizationID,omitempty" json:"CustomizationID,omitempty"`
	CustomizationID string   `xml:",chardata" json:",omitempty"`
}

type CDescription__cbc struct {
	XMLName     xml.Name `xml:"Description,omitempty" json:"Description,omitempty"`
	Description string   `xml:",chardata" json:",omitempty"`
}

type CDocumentCurrencyCode__cbc struct {
	XMLName              xml.Name `xml:"DocumentCurrencyCode,omitempty" json:"DocumentCurrencyCode,omitempty"`
	DocumentCurrencyCode string   `xml:",chardata" json:",omitempty"`
}

type CElectronicMail__cbc struct {
	XMLName        xml.Name `xml:"ElectronicMail,omitempty" json:"ElectronicMail,omitempty"`
	ElectronicMail string   `xml:",chardata" json:",omitempty"`
}

type CEndDate__cbc struct {
	XMLName xml.Name `xml:"EndDate,omitempty" json:"EndDate,omitempty"`
	EndDate string   `xml:",chardata" json:",omitempty"`
}

type CID__cbc struct {
	XMLName xml.Name `xml:"ID,omitempty" json:"ID,omitempty"`
	ID      string   `xml:",chardata" json:",omitempty"`
}

type CIdentificationCode__cbc struct {
	XMLName            xml.Name `xml:"IdentificationCode,omitempty" json:"IdentificationCode,omitempty"`
	IdentificationCode string   `xml:",chardata" json:",omitempty"`
}

type CInvoiceTypeCode__cbc struct {
	XMLName         xml.Name `xml:"InvoiceTypeCode,omitempty" json:"InvoiceTypeCode,omitempty"`
	InvoiceTypeCode string   `xml:",chardata" json:",omitempty"`
}

type CInvoicedQuantity__cbc struct {
	XMLName          xml.Name `xml:"InvoicedQuantity,omitempty" json:"InvoicedQuantity,omitempty"`
	AttrunitCode     string   `xml:"unitCode,attr"  json:",omitempty"`
	InvoicedQuantity string   `xml:",chardata" json:",omitempty"`
}

type CIssueDate__cbc struct {
	XMLName   xml.Name `xml:"IssueDate,omitempty" json:"IssueDate,omitempty"`
	IssueDate string   `xml:",chardata" json:",omitempty"`
}

type CItemClassificationCode__cbc struct {
	XMLName                xml.Name `xml:"ItemClassificationCode,omitempty" json:"ItemClassificationCode,omitempty"`
	AttrlistID             string   `xml:"listID,attr"  json:",omitempty"`
	ItemClassificationCode string   `xml:",chardata" json:",omitempty"`
}

type CLineExtensionAmount__cbc struct {
	XMLName             xml.Name `xml:"LineExtensionAmount,omitempty" json:"LineExtensionAmount,omitempty"`
	AttrcurrencyID      string   `xml:"currencyID,attr"  json:",omitempty"`
	LineExtensionAmount string   `xml:",chardata" json:",omitempty"`
}

type CLineID__cbc struct {
	XMLName xml.Name `xml:"LineID,omitempty" json:"LineID,omitempty"`
	LineID  string   `xml:",chardata" json:",omitempty"`
}

type CName__cbc struct {
	XMLName xml.Name `xml:"Name,omitempty" json:"Name,omitempty"`
	Name    string   `xml:",chardata" json:",omitempty"`
}

type CNote__cbc struct {
	XMLName xml.Name `xml:"Note,omitempty" json:"Note,omitempty"`
	Note    string   `xml:",chardata" json:",omitempty"`
}

type CPayableAmount__cbc struct {
	XMLName        xml.Name `xml:"PayableAmount,omitempty" json:"PayableAmount,omitempty"`
	AttrcurrencyID string   `xml:"currencyID,attr"  json:",omitempty"`
	PayableAmount  string   `xml:",chardata" json:",omitempty"`
}

type CPaymentMeansCode__cbc struct {
	XMLName          xml.Name `xml:"PaymentMeansCode,omitempty" json:"PaymentMeansCode,omitempty"`
	PaymentMeansCode string   `xml:",chardata" json:",omitempty"`
}

type CPercent__cbc struct {
	XMLName xml.Name `xml:"Percent,omitempty" json:"Percent,omitempty"`
	Percent string   `xml:",chardata" json:",omitempty"`
}

type CPostalZone__cbc struct {
	XMLName    xml.Name `xml:"PostalZone,omitempty" json:"PostalZone,omitempty"`
	PostalZone string   `xml:",chardata" json:",omitempty"`
}

type CPriceAmount__cbc struct {
	XMLName        xml.Name `xml:"PriceAmount,omitempty" json:"PriceAmount,omitempty"`
	AttrcurrencyID string   `xml:"currencyID,attr"  json:",omitempty"`
	PriceAmount    string   `xml:",chardata" json:",omitempty"`
}

type CRegistrationName__cbc struct {
	XMLName          xml.Name `xml:"RegistrationName,omitempty" json:"RegistrationName,omitempty"`
	RegistrationName string   `xml:",chardata" json:",omitempty"`
}

type CStartDate__cbc struct {
	XMLName   xml.Name `xml:"StartDate,omitempty" json:"StartDate,omitempty"`
	StartDate string   `xml:",chardata" json:",omitempty"`
}

type CStreetName__cbc struct {
	XMLName    xml.Name `xml:"StreetName,omitempty" json:"StreetName,omitempty"`
	StreetName string   `xml:",chardata" json:",omitempty"`
}

type CTaxAmount__cbc struct {
	XMLName        xml.Name `xml:"TaxAmount,omitempty" json:"TaxAmount,omitempty"`
	AttrcurrencyID string   `xml:"currencyID,attr"  json:",omitempty"`
	TaxAmount      string   `xml:",chardata" json:",omitempty"`
}

type CTaxCurrencyCode__cbc struct {
	XMLName         xml.Name `xml:"TaxCurrencyCode,omitempty" json:"TaxCurrencyCode,omitempty"`
	TaxCurrencyCode string   `xml:",chardata" json:",omitempty"`
}

type CTaxExclusiveAmount__cbc struct {
	XMLName            xml.Name `xml:"TaxExclusiveAmount,omitempty" json:"TaxExclusiveAmount,omitempty"`
	AttrcurrencyID     string   `xml:"currencyID,attr"  json:",omitempty"`
	TaxExclusiveAmount string   `xml:",chardata" json:",omitempty"`
}

type CTaxInclusiveAmount__cbc struct {
	XMLName            xml.Name `xml:"TaxInclusiveAmount,omitempty" json:"TaxInclusiveAmount,omitempty"`
	AttrcurrencyID     string   `xml:"currencyID,attr"  json:",omitempty"`
	TaxInclusiveAmount string   `xml:",chardata" json:",omitempty"`
}

type CTaxableAmount__cbc struct {
	XMLName        xml.Name `xml:"TaxableAmount,omitempty" json:"TaxableAmount,omitempty"`
	AttrcurrencyID string   `xml:"currencyID,attr"  json:",omitempty"`
	TaxableAmount  string   `xml:",chardata" json:",omitempty"`
}

type CTelephone__cbc struct {
	XMLName   xml.Name `xml:"Telephone,omitempty" json:"Telephone,omitempty"`
	Telephone string   `xml:",chardata" json:",omitempty"`
}

type CInvoice2__ubl struct {
	XMLName                       xml.Name                      `xml:"Invoice,omitempty" json:"Invoice,omitempty"`
	AttrXmlnscac                  string                        `xml:"xmlns cac,attr"  json:",omitempty"`
	AttrXmlnscbc                  string                        `xml:"xmlns cbc,attr"  json:",omitempty"`
	AttrXmlnsubl                  string                        `xml:"xmlns ubl,attr"  json:",omitempty"`
	CAccountingCustomerParty__cac CAccountingCustomerParty__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 AccountingCustomerParty,omitempty" json:"AccountingCustomerParty,omitempty"`
	CAccountingSupplierParty__cac CAccountingSupplierParty__cac `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 AccountingSupplierParty,omitempty" json:"AccountingSupplierParty,omitempty"`
	CBuyerReference__cbc          CBuyerReference__cbc          `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 BuyerReference,omitempty" json:"BuyerReference,omitempty"`
	CCustomizationID__cbc         CCustomizationID__cbc         `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 CustomizationID,omitempty" json:"CustomizationID,omitempty"`
	CDocumentCurrencyCode__cbc    CDocumentCurrencyCode__cbc    `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 DocumentCurrencyCode,omitempty" json:"DocumentCurrencyCode,omitempty"`
	CID__cbc                      CID__cbc                      `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 ID,omitempty" json:"ID,omitempty"`
	CInvoiceLine__cac             []CInvoiceLine__cac           `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 InvoiceLine,omitempty" json:"InvoiceLine,omitempty"`
	CInvoiceTypeCode__cbc         CInvoiceTypeCode__cbc         `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 InvoiceTypeCode,omitempty" json:"InvoiceTypeCode,omitempty"`
	CIssueDate__cbc               CIssueDate__cbc               `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 IssueDate,omitempty" json:"IssueDate,omitempty"`
	CLegalMonetaryTotal__cac      CLegalMonetaryTotal__cac      `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 LegalMonetaryTotal,omitempty" json:"LegalMonetaryTotal,omitempty"`
	CNote__cbc                    CNote__cbc                    `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 Note,omitempty" json:"Note,omitempty"`
	CPaymentMeans__cac            CPaymentMeans__cac            `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 PaymentMeans,omitempty" json:"PaymentMeans,omitempty"`
	CPaymentTerms__cac            CPaymentTerms__cac            `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 PaymentTerms,omitempty" json:"PaymentTerms,omitempty"`
	CTaxCurrencyCode__cbc         CTaxCurrencyCode__cbc         `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2 TaxCurrencyCode,omitempty" json:"TaxCurrencyCode,omitempty"`
	CTaxTotal__cac                CTaxTotal__cac                `xml:"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2 TaxTotal,omitempty" json:"TaxTotal,omitempty"`
}

///////////////////////////
